# k8s variables

microk8s_version: "1.31/stable"
microk8s_disable_snap_autoupdate: false

# plugin configuration
microk8s_dns_resolvers: 8.8.8.8,8.8.4.4
registry_size: 20Gi
microk8s_plugins:
  dns: "{{ microk8s_dns_resolvers }}"     # CoreDNS
  host-access: false                       # Allow Pods connecting to Host services smoothly
  ingress: true                           # Ingress controller for external access
  metrics-server: false                    # K8s Metrics Server for API access to service metrics
  rbac: true                              # Role-Based Access Control for authorisation
  hostpath-storage: true                  # Storage class; allocates storage from host directory
  registry: "size={{ registry_size }}"    # Private image registry exposed on localhost:32000
  dashboard: false                         # The Kubernetes dashboard
  ambassador: false                       # Ambassador API Gateway and Ingress
  cilium: false                           # SDN, fast with full network policy
  fluentd: false                          # Elasticsearch-Fluentd-Kibana logging and monitoring
  gpu: false                              # Automatic enablement of Nvidia CUDA
  helm: true                              # Helm 2 - the package manager for Kubernetes
  helm3: true                             # Helm 3 - Kubernetes package manager
  cert-manager: true
  storage: true
  observability: false
  traefik: false                           # another ingress

# awx variables
awxoperater_version: "2.4.0"

